//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achevement 1 Desc.
        /// </summary>
        public static string Achievement1Desc {
            get {
                return ResourceManager.GetString("Achievement1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Achievement1Pic {
            get {
                object obj = ResourceManager.GetObject("Achievement1Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title 1.
        /// </summary>
        public static string Achievement1Title {
            get {
                return ResourceManager.GetString("Achievement1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement 2 Desc.
        /// </summary>
        public static string Achievement2Desc {
            get {
                return ResourceManager.GetString("Achievement2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Achievement2Pic {
            get {
                object obj = ResourceManager.GetObject("Achievement2Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title 2.
        /// </summary>
        public static string Achievement2Title {
            get {
                return ResourceManager.GetString("Achievement2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement 3 Desc.
        /// </summary>
        public static string Achievement3Desc {
            get {
                return ResourceManager.GetString("Achievement3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Achievement3Pic {
            get {
                object obj = ResourceManager.GetObject("Achievement3Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title 3.
        /// </summary>
        public static string Achievement3Title {
            get {
                return ResourceManager.GetString("Achievement3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple classic checker.
        /// </summary>
        public static string Item1Desc {
            get {
                return ResourceManager.GetString("Item1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Item1Pic {
            get {
                object obj = ResourceManager.GetObject("Item1Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic checker.
        /// </summary>
        public static string Item1Title {
            get {
                return ResourceManager.GetString("Item1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple classic board.
        /// </summary>
        public static string Item2Desc {
            get {
                return ResourceManager.GetString("Item2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Item2Pic {
            get {
                object obj = ResourceManager.GetObject("Item2Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic board.
        /// </summary>
        public static string Item2Title {
            get {
                return ResourceManager.GetString("Item2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple animation of removement.
        /// </summary>
        public static string Item3Desc {
            get {
                return ResourceManager.GetString("Item3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Item3Pic {
            get {
                object obj = ResourceManager.GetObject("Item3Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic animation.
        /// </summary>
        public static string Item3Title {
            get {
                return ResourceManager.GetString("Item3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProfilePic1 {
            get {
                object obj = ResourceManager.GetObject("ProfilePic1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
